name: phpcs

on:
  - push

jobs:
  phpcs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          tools: phpcs
      - run: phpcs --standard=PSR12 .
